# ======= Firewalld =================
- name: Enable firewalld
  service: name=firewalld state=started enabled=yes

- name: Firewalld configuration for ES
  firewalld:
   port: 9200-9300/tcp
   permanent: true
   state: enabled
   immediate: yes

- name: Firewalld configuration for ES transportation layer
  firewalld:
   port: 9300-9400/tcp
   permanent: true
   state: enabled
   immediate: yes

- name: Firewalld configuration for http
  firewalld:
   port: 80/tcp
   permanent: true
   state: enabled
   immediate: yes

- name: Firewalld configuration for https
  firewalld:
   port: 443/tcp
   permanent: true
   state: enabled
   immediate: yes

- name: Reload firewalld
  systemd:
   name: firewalld
   state: restarted

